Repository rtCamp/godam, pull requests merged in 2025-07, with the labels that each got.

#482 Extend Media Library features
  inc/classes/class-plugin.php
  inc/classes/media-library/class-media-folder-create-zip.php
  inc/classes/media-library/class-media-folder-utils.php
  inc/classes/media-library/class-media-folders-rest-api.php
  inc/classes/rest-api/class-media-library.php
  inc/classes/taxonomies/class-media-folders.php
  inc/helpers/autoloader.php
  pages/media-library/App.js
  pages/media-library/components/folder-tree/BookmarkItem.jsx
  pages/media-library/components/folder-tree/BookmarkTab.jsx
  pages/media-library/components/folder-tree/ContextMenu.jsx
  pages/media-library/components/folder-tree/FolderTree.jsx
  pages/media-library/components/folder-tree/TreeItem.jsx
  pages/media-library/components/folder-tree/css/bookmark.scss
  pages/media-library/components/folder-tree/css/context-menu.scss
  pages/media-library/components/folder-tree/css/snackbar.scss
  pages/media-library/components/folder-tree/css/tree-item.scss
  pages/media-library/components/modal/DeleteModal.jsx
  pages/media-library/components/modal/FolderCreationModal.jsx
  pages/media-library/components/modal/RenameModal.jsx
  pages/media-library/redux/api/folders.js
  pages/media-library/redux/slice/folders.js
Labels: Feature

#629 GH 628: Fix uppy object to enforce max file size restrictions
  assets/src/js/godam-recorder/index.js
Labels: Bug

#600 Prevent duplicate attachments on rapid search input
  pages/video-editor/components/media-grid/MediaGrid.jsx
Labels: Bug

#690 Fix QA issues for 1.3.0
  assets/src/js/media-library/views/media-frame-select.js
  inc/classes/class-video-metadata.php
  pages/video-editor/components/LayerSelector.jsx
Labels: Bug

#693 Fix - QA Issues
  assets/src/js/admin.js
  pages/analytics/Video.js
  pages/video-editor/components/LayerSelector.jsx
  pages/video-editor/components/layer-selector.scss
Labels: Bug

#696 Add user settings for CPT visibility in links
  inc/classes/class-video-permalinks.php
  inc/classes/post-types/class-godam-video.php
Labels: Enhancement, Feature, Plugin

#751 Feat: Add CSS to Featured video
  assets/src/css/godam-featured-video.scss
  assets/src/js/godam-player/frontend.js
  assets/src/js/wc-featured-video-gallery.js
Labels: Enhancement

#771 Feat/product gallery UI fixes
  assets/src/css/godam-video-popup.scss
  assets/src/js/woocommerce/godam-product-gallery/modal.js
  assets/src/js/woocommerce/godam-product-gallery/sidebar.js
  inc/classes/shortcodes/class-godam-product-gallery.php
Labels: Enhancement

#772 Fix feature product video UI modal for Woocommerce integration
  assets/src/css/godam-featured-video.scss
  assets/src/css/godam-video-popup.scss
  assets/src/js/godam-player/frontend.js
  assets/src/js/woocommerce/featured-video/wc-featured-video-gallery.js
Labels: Enhancement

#792 WooCommerce Product Gallery & Video UI Fixes for Mobile and Desktop
  assets/src/css/godam-product-gallery.scss
  assets/src/css/godam-video-popup.scss
  assets/src/images/cropped-video-thumbnail-default.png
  inc/classes/shortcodes/class-godam-product-gallery.php
  inc/classes/woocommerce/class-wc-featured-video-gallery.php
Labels: Enhancement

#793 WooCommerce Integration: Sidebar Enhancements & Mini Cart UI Update
  assets/src/css/_common.scss
  assets/src/css/admin.scss
  assets/src/css/godam-player.scss
  assets/src/js/woocommerce/admin/wc-add-to-product.js
  assets/src/js/woocommerce/godam-product-gallery/modal.js
  assets/src/js/woocommerce/godam-product-gallery/sidebar.js
  inc/classes/woocommerce/class-wc-product-gallery-video-markup.php
  inc/classes/woocommerce/class-wc-product-video-gallery.php
Labels: Enhancement
